export const TALIMY_UI_SUPPORTED_EXPORTS = [
  "cn",
  "Badge",
  "badgeVariants",
  "Button",
  "buttonVariants",
  "Card",
  "CardHeader",
  "CardTitle",
  "CardDescription",
  "CardContent",
  "CardFooter",
  "Input",
  "Label",
  "TALIMY_UI_PACKAGE_STATUS",
] as const
