export const TALIMY_UI_SUPPORTED_EXPORTS = [
  "cn",
  "TALIMY_UI_PACKAGE_STATUS",
  "TALIMY_UI_COMPONENT_SOURCE",
  "TALIMY_UI_LOCAL_WEB_COMPONENTS_DEPRECATED",
] as const

export const TALIMY_UI_COMPONENT_SOURCE = "packages/ui" as const

export const TALIMY_UI_LOCAL_WEB_COMPONENTS_DEPRECATED = true as const
